name: Build

on:
  create:
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install node-gyp
        run: npm install -g node-gyp

      - run: npm install
        env:
          NO_PREBUILD: true

      - name: Build Addon
        run: node-gyp rebuild

      - name: Package
        run: node script/prebuild.js pack

      - name: Upload prebuilt binary
        uses: softprops/action-gh-release@v2
        with:
          files: prebuilds/*
